%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%       Written by Micha Anholt, Metalink Broadband
%       Contact   micha_a@metalinkbb.com
%       www.metalinkbb.com
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%function bits = read_bits (name)
% input : file name that contains rows with byte in each row
% output: column of bits generated byte by byte with lsb first
%

function bits = read_bits (name)
fid = fopen (name,'rt');
hex_read = fscanf(fid,'%s\n'); % appends all words
fclose(fid);
bytes = reshape(hex_read,2,length(hex_read)/2)'; % resahpe to bytes
bytes_dec = hex2dec(bytes);     % convert to int
bits = bitand(floor(bytes_dec*(2.^-(0:7))),1); % separate to bits
bits=bits';                                    % 
bits=bits(:);                                  % create bit stream in correct order
